// PusulaKira API — local SQLite-backed rental and apartment management core.
const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { DatabaseSync } = require('node:sqlite');
const root = __dirname, port = Number(process.env.PORT || 3000);
const assetVersion = file => { try { return Math.round(fs.statSync(path.join(root, file)).mtimeMs).toString(36) } catch { return '0' } };
const ASSET_VERSIONS = { 'app.js': assetVersion('app.js'), 'styles.css': assetVersion('styles.css') };
const db = new DatabaseSync(path.join(root, 'kirapanel.db'));
const uploads = path.join(root, 'uploads'); fs.mkdirSync(uploads, { recursive: true });

db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY,name TEXT NOT NULL,iban TEXT NOT NULL DEFAULT '',owner_name TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS tenants(id INTEGER PRIMARY KEY,name TEXT NOT NULL,contact TEXT UNIQUE NOT NULL,property_id INTEGER NOT NULL,rent INTEGER NOT NULL,payment_day INTEGER NOT NULL,contract_end TEXT NOT NULL,termination_at TEXT,termination_note TEXT,contract_start TEXT,contract_months INTEGER,renewal_date TEXT,contract_duration_days INTEGER,rental_category TEXT,password_hash TEXT,FOREIGN KEY(property_id) REFERENCES properties(id));
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,contact TEXT UNIQUE NOT NULL,role TEXT NOT NULL CHECK(role IN ('agent','tenant')),tenant_id INTEGER,created_at TEXT NOT NULL,full_name TEXT,password_hash TEXT,FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL,period TEXT NOT NULL,amount INTEGER NOT NULL,due_date TEXT NOT NULL,status TEXT NOT NULL,receipt_name TEXT,receipt_required INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS advance_requests(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL,months INTEGER NOT NULL,amount INTEGER NOT NULL,note TEXT,status TEXT NOT NULL DEFAULT 'İnceleme bekliyor',review_note TEXT,created_at TEXT NOT NULL,reviewed_at TEXT,FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS announcements(id INTEGER PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tickets(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL,type TEXT NOT NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Yeni',reply TEXT,created_at TEXT NOT NULL,updated_at TEXT,category TEXT,priority TEXT,FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS bank_matches(id INTEGER PRIMARY KEY,reference TEXT NOT NULL,amount INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sites(id INTEGER PRIMARY KEY,name TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',block_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS blocks(id INTEGER PRIMARY KEY,site_id INTEGER NOT NULL,name TEXT NOT NULL,FOREIGN KEY(site_id) REFERENCES sites(id));
CREATE TABLE IF NOT EXISTS units(id INTEGER PRIMARY KEY,block_id INTEGER NOT NULL,unit_no TEXT NOT NULL,occupancy TEXT NOT NULL DEFAULT 'Boş',FOREIGN KEY(block_id) REFERENCES blocks(id));
CREATE TABLE IF NOT EXISTS activity_logs(id INTEGER PRIMARY KEY,user_id INTEGER,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id INTEGER,details TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));`);
const column = (table, name, definition) => { if (!db.prepare(`PRAGMA table_info(${table})`).all().some(x => x.name === name)) db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`); };
[['tenants','termination_at','TEXT'],['tenants','termination_note','TEXT'],['tenants','contract_start','TEXT'],['tenants','contract_months','INTEGER'],['tenants','renewal_date','TEXT'],['tenants','contract_duration_days','INTEGER'],['tenants','rental_category','TEXT'],['tenants','password_hash','TEXT'],['users','full_name','TEXT'],['users','password_hash','TEXT'],['tickets','category','TEXT'],['tickets','priority','TEXT']].forEach(x => column(...x));
column('properties','address','TEXT');
column('properties','manager_id','INTEGER');
column('announcements','manager_id','INTEGER');
column('bank_matches','manager_id','INTEGER');
column('sites','manager_id','INTEGER');
(function backfillManagerOwnership() {
  const owner = db.prepare("SELECT id FROM users WHERE role='agent' ORDER BY id ASC LIMIT 1").get();
  if (!owner) return;
  for (const table of ['properties', 'announcements', 'bank_matches', 'sites']) db.prepare(`UPDATE ${table} SET manager_id=? WHERE manager_id IS NULL`).run(owner.id);
})();

const now = () => new Date().toISOString(), period = () => now().slice(0, 7), clean = x => String(x || '').trim();
const nameKey = x => clean(x).replace(/\s+/g, ' ').toLocaleLowerCase('tr-TR');
const validPassword = x => typeof x === 'string' && x.length >= 6 && x.length <= 128;
const makeHash = x => { const s = crypto.randomBytes(16).toString('hex'); return `${s}:${crypto.scryptSync(x, s, 64).toString('hex')}`; };
const checkHash = (x, saved) => { if (!validPassword(x) || !saved) return false; const [s, expected] = String(saved).split(':'); if (!s || !expected) return false; const actual = crypto.scryptSync(x, s, 64).toString('hex'); return actual.length === expected.length && crypto.timingSafeEqual(Buffer.from(actual, 'hex'), Buffer.from(expected, 'hex')); };
const json = (res, status, data) => { res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}); res.end(JSON.stringify(data)); };
const parse = req => new Promise((resolve, reject) => { let raw = ''; req.on('data', c => { raw += c; if (raw.length > 12 * 1024 * 1024) reject(Error('İstek çok büyük.')); }); req.on('end', () => { try { resolve(JSON.parse(raw || '{}')); } catch { reject(Error('Geçersiz JSON.')); } }); });
function user(req) { const token = String(req.headers.authorization || '').replace(/^Bearer\s+/i, ''); return token ? db.prepare('SELECT u.id,u.full_name,u.role,u.tenant_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(token, Date.now()) : null; }
function guard(req, res, role) { const u = user(req); if (!u || (role && u.role !== role)) { json(res, 403, {error: role === 'agent' ? 'Yönetici oturumu gerekir.' : 'Geçerli oturum gerekir.'}); return null; } return u; }
function audit(u, action, entity, id, detail='') { db.prepare('INSERT INTO activity_logs(user_id,action,entity_type,entity_id,details,created_at) VALUES(?,?,?,?,?,?)').run(u?.id || null, action, entity, id || null, clean(detail).slice(0,500), now()); }
function session(u) { const token = crypto.randomBytes(32).toString('hex'); db.prepare('DELETE FROM sessions WHERE expires_at<?').run(Date.now()); db.prepare('INSERT INTO sessions(token,user_id,expires_at) VALUES(?,?,?)').run(token,u.id,Date.now()+30*86400000); return token; }
const validDate = v => /^\d{4}-\d{2}-\d{2}$/.test(v) && !Number.isNaN(new Date(`${v}T12:00:00`).getTime());
const daysBetween = (a,b) => Math.round((new Date(`${b}T12:00:00`) - new Date(`${a}T12:00:00`))/86400000);

async function registerManager(req,res) { const b=await parse(req), name=clean(b.name), contact=`manager:${nameKey(name)}`; if(name.length<2||!validPassword(b.password)) return json(res,400,{error:'Ad soyad ve en az 6 karakter parola girin.'}); if(db.prepare('SELECT 1 FROM users WHERE contact=?').get(contact)) return json(res,409,{error:'Bu adla kayıtlı yönetici hesabı var. Giriş yapmayı deneyin.'}); const r=db.prepare('INSERT INTO users(contact,role,created_at,full_name,password_hash) VALUES(?,?,?,?,?)').run(contact,'agent',now(),name,makeHash(b.password)), u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid); audit(u,'Yönetici hesabı oluşturuldu','user',u.id); json(res,201,{ok:true,token:session(u),role:'agent',name}); }
const loginAttempts=new Map();
const LOGIN_MAX_ATTEMPTS=8, LOGIN_WINDOW_MS=15*60000, LOGIN_LOCKOUT_MS=10*60000;
function loginThrottleKey(role,name){return `${role}:${nameKey(name)}`}
function loginBlocked(key){const rec=loginAttempts.get(key);if(!rec)return 0;if(rec.lockedUntil&&rec.lockedUntil>Date.now())return rec.lockedUntil-Date.now();if(rec.lockedUntil&&rec.lockedUntil<=Date.now()){loginAttempts.delete(key);return 0}return 0}
function loginFailed(key){const rec=loginAttempts.get(key)||{count:0,firstAt:Date.now()};if(Date.now()-rec.firstAt>LOGIN_WINDOW_MS){rec.count=0;rec.firstAt=Date.now()}rec.count++;if(rec.count>=LOGIN_MAX_ATTEMPTS)rec.lockedUntil=Date.now()+LOGIN_LOCKOUT_MS;loginAttempts.set(key,rec)}
function loginSucceeded(key){loginAttempts.delete(key)}
async function login(req,res) { const b=await parse(req), role=b.role==='tenant'?'tenant':'agent', name=clean(b.name); if(!name||!validPassword(b.password)) return json(res,400,{error:'Ad soyad ve parola girin.'}); const throttleKey=loginThrottleKey(role,name), blockedMs=loginBlocked(throttleKey); if(blockedMs>0) return json(res,429,{error:`Çok fazla başarısız deneme. ${Math.ceil(blockedMs/60000)} dakika sonra tekrar deneyin.`}); let u; if(role==='agent') u=db.prepare("SELECT * FROM users WHERE role='agent' AND lower(full_name)=lower(?)").get(name); else { const t=db.prepare('SELECT * FROM tenants WHERE lower(name)=lower(?) AND termination_at IS NULL ORDER BY id DESC LIMIT 1').get(name); if(t&&checkHash(b.password,t.password_hash)){u=db.prepare("SELECT * FROM users WHERE tenant_id=? AND role='tenant'").get(t.id); if(!u){const r=db.prepare('INSERT INTO users(contact,role,tenant_id,created_at,full_name,password_hash) VALUES(?,?,?,?,?,?)').run(`tenant:${t.id}`,'tenant',t.id,now(),t.name,t.password_hash);u=db.prepare('SELECT * FROM users WHERE id=?').get(r.lastInsertRowid)}}} if(!u||!checkHash(b.password,u.password_hash)) { loginFailed(throttleKey); return json(res,401,{error:'Ad soyad veya parola hatalı.'}); } loginSucceeded(throttleKey); audit(u,'Giriş yapıldı','session',u.id); json(res,200,{ok:true,token:session(u),role:u.role,name:u.full_name||name}); }
function logout(req,res) { const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,''); if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(token); json(res,200,{ok:true}); }
async function updateProfile(req,res) { const u=guard(req,res,'agent');if(!u)return;const b=await parse(req),name=clean(b.fullName);if(name.length<2||name.length>80)return json(res,400,{error:'Ad soyad en az 2, en fazla 80 karakter olmalıdır.'});db.prepare('UPDATE users SET full_name=? WHERE id=?').run(name,u.id);audit(u,'Profil güncellendi','user',u.id);json(res,200,{ok:true,name}); }
async function updatePassword(req,res) { const u=guard(req,res,'agent');if(!u)return;const b=await parse(req),current=String(b.currentPassword||''),next=String(b.newPassword||'');const row=db.prepare('SELECT password_hash FROM users WHERE id=?').get(u.id);if(!checkHash(current,row?.password_hash))return json(res,400,{error:'Mevcut parola hatalı.'});if(!validPassword(next))return json(res,400,{error:'Yeni parola en az 6 karakter olmalıdır.'});db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(makeHash(next),u.id);audit(u,'Parola güncellendi','user',u.id);json(res,200,{ok:true}); }
function paymentStatusCode(value){return value==='Ödendi'?'PAID':value==='Feshedildi'?'TERMINATED':value==='Silindi'?'DELETED':value==='Dekont yüklendi'?'RECEIPT_UPLOADED':'PENDING'}
function portal(req,res) { const u=guard(req,res); if(!u)return; if(u.role==='agent') return json(res,200,{role:'agent',summary:db.prepare('SELECT COUNT(*) tenants,COALESCE(SUM(t.rent),0) expected FROM tenants t JOIN properties p ON p.id=t.property_id WHERE t.termination_at IS NULL AND p.manager_id=?').get(u.id)}); const p=db.prepare(`SELECT t.id,t.name,t.rent,t.payment_day,t.contract_start,t.contract_end,t.contract_duration_days,t.rental_category,p.name property,p.iban,p.owner_name,pay.status,pay.due_date,pay.receipt_name,pay.receipt_required FROM tenants t JOIN properties p ON p.id=t.property_id LEFT JOIN payments pay ON pay.tenant_id=t.id AND pay.period=? WHERE t.id=?`).get(period(),u.tenant_id); if(p)p.payment_status_code=paymentStatusCode(p.status); json(res,200,{role:'tenant',profile:p}); }
async function createTenant(req,res) { const u=guard(req,res,'agent');if(!u)return;const b=await parse(req),name=clean(b.name),property=clean(b.property),start=clean(b.contractStart),end=clean(b.contractEndManual||b.contractEnd),rent=Number(b.rent),day=Number(b.day),phone=clean(b.phone||b.contact);if(!name||!property||!phone||!Number.isFinite(rent)||rent<=0||!Number.isInteger(day)||day<1||day>31||!validDate(start)||!validDate(end)||!validPassword(b.password))return json(res,400,{error:'Kiracı, telefon, kira, tarihler ve en az 6 karakter giriş parolası zorunludur.'});if(db.prepare('SELECT 1 FROM tenants WHERE contact=?').get(phone))return json(res,409,{error:'Bu telefon numarasıyla kayıtlı bir kiracı var.'});const duration=daysBetween(start,end);if(duration<1)return json(res,400,{error:'Sözleşme bitiş tarihi başlangıçtan sonra olmalıdır.'});const contact=phone,p=db.prepare('INSERT INTO properties(name,iban,owner_name,address,manager_id) VALUES(?,?,?,?,?)').run(property,clean(b.iban).replace(/\s/g,'').toUpperCase(),clean(b.owner)||'Ev sahibi',clean(b.address).slice(0,300),u.id),t=db.prepare('INSERT INTO tenants(name,contact,property_id,rent,payment_day,contract_end,contract_start,contract_months,renewal_date,contract_duration_days,rental_category,password_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(name,contact,p.lastInsertRowid,rent,day,end,start,Math.round(duration/30),end,duration,null,makeHash(b.password));db.prepare('INSERT INTO payments(tenant_id,period,amount,due_date,status) VALUES(?,?,?,?,?)').run(t.lastInsertRowid,period(),rent,`${period()}-${String(day).padStart(2,'0')}`,'Bekliyor');audit(u,'Kiracı kaydı oluşturuldu','tenant',Number(t.lastInsertRowid),name);json(res,201,{ok:true,tenantId:Number(t.lastInsertRowid),renewalDate:end,durationDays:duration}); }
function tenantList(req,res) { const u=guard(req,res,'agent');if(!u)return;const items=db.prepare(`SELECT t.id,t.name,t.contact,t.rent,t.payment_day,t.contract_start,t.contract_end,t.contract_duration_days,t.rental_category,t.termination_at,t.termination_note,p.name property,p.owner_name,p.iban,p.address,pay.period,pay.due_date,pay.status,pay.receipt_required,pay.receipt_name FROM tenants t JOIN properties p ON p.id=t.property_id LEFT JOIN payments pay ON pay.tenant_id=t.id AND pay.period=? WHERE p.manager_id=? ORDER BY t.id DESC`).all(period(),u.id).map(item=>({...item,payment_status_code:paymentStatusCode(item.status)}));json(res,200,{items}); }
async function managerAction(req,res) { const u=guard(req,res,'agent');if(!u)return;const b=await parse(req),id=Number(b.tenantId),action=clean(b.action);if(!id||!db.prepare('SELECT 1 FROM tenants t JOIN properties p ON p.id=t.property_id WHERE t.id=? AND p.manager_id=?').get(id,u.id))return json(res,404,{error:'Kiracı bulunamadı.'});let label;if(action==='terminate'){const note=clean(b.note);if(!note)return json(res,400,{error:'Fesih notu zorunludur.'});db.prepare('UPDATE tenants SET termination_at=?,termination_note=? WHERE id=?').run(now(),note.slice(0,500),id);db.prepare("UPDATE payments SET status='Feshedildi' WHERE tenant_id=? AND period=?").run(id,period());label='Sözleşme feshedildi'}else if(action==='mark-paid'){db.prepare("UPDATE payments SET status='Ödendi' WHERE tenant_id=? AND period=?").run(id,period());label='Ödeme onaylandı'}else if(action==='delete-payment'){db.prepare("UPDATE payments SET status='Silindi' WHERE tenant_id=? AND period=?").run(id,period());label='Ödeme kaydı silindi'}else if(action==='receipt-required'){db.prepare('UPDATE payments SET receipt_required=? WHERE tenant_id=? AND period=?').run(b.required?1:0,id,period());label=b.required?'Dekont zorunlu yapıldı':'Dekont isteğe bağlı yapıldı'}else return json(res,400,{error:'Geçersiz yönetici işlemi.'});audit(u,label,'tenant',id);json(res,200,{ok:true}); }
function tenantManagerId(tenantId) { const row=db.prepare('SELECT p.manager_id FROM tenants t JOIN properties p ON p.id=t.property_id WHERE t.id=?').get(tenantId); return row?row.manager_id:null; }
async function announcementApi(req,res) { const u=guard(req,res);if(!u)return;const managerId=u.role==='agent'?u.id:tenantManagerId(u.tenant_id);if(req.method==='GET')return json(res,200,{items:managerId?db.prepare('SELECT * FROM announcements WHERE manager_id=? ORDER BY id DESC LIMIT 50').all(managerId):[]});if(u.role!=='agent')return json(res,403,{error:'Yönetici oturumu gerekir.'});const b=await parse(req),title=clean(b.title).slice(0,100),text=clean(b.body).slice(0,1000);if(!title||!text)return json(res,400,{error:'Duyuru başlığı ve metni zorunludur.'});const r=db.prepare('INSERT INTO announcements(title,body,created_at,manager_id) VALUES(?,?,?,?)').run(title,text,now(),u.id);audit(u,'Duyuru yayınlandı','announcement',Number(r.lastInsertRowid),title);json(res,201,{ok:true,id:Number(r.lastInsertRowid)}); }
async function ticketApi(req,res) { const u=guard(req,res);if(!u)return;if(req.method==='GET'){const sql=u.role==='agent'?'SELECT k.*,t.name tenant FROM tickets k JOIN tenants t ON t.id=k.tenant_id JOIN properties p ON p.id=t.property_id WHERE p.manager_id=? ORDER BY k.id DESC':'SELECT k.*,t.name tenant FROM tickets k JOIN tenants t ON t.id=k.tenant_id WHERE k.tenant_id=? ORDER BY k.id DESC';return json(res,200,{items:u.role==='agent'?db.prepare(sql).all(u.id):db.prepare(sql).all(u.tenant_id)})}const b=await parse(req);if(u.role==='tenant'){const message=clean(b.message).slice(0,500),type=b.type==='Şikâyet'?'Şikâyet':'İstek',category=['Bakım','Temizlik','Güvenlik','Ödeme','Diğer'].includes(b.category)?b.category:'Diğer',priority=['Normal','Yüksek','Acil'].includes(b.priority)?b.priority:'Normal';if(message.length<5)return json(res,400,{error:'Lütfen en az 5 karakterlik açıklama yazın.'});const r=db.prepare('INSERT INTO tickets(tenant_id,type,category,priority,message,created_at) VALUES(?,?,?,?,?,?)').run(u.tenant_id,type,category,priority,message,now());audit(u,'Destek talebi oluşturuldu','ticket',Number(r.lastInsertRowid),`${type}: ${category}`);return json(res,201,{ok:true,id:Number(r.lastInsertRowid)})}const id=Number(b.id),status=['Yeni','İncelendi','İşlemde','Çözüldü'].includes(b.status)?b.status:'İncelendi';if(!id||!db.prepare('SELECT 1 FROM tickets k JOIN tenants t ON t.id=k.tenant_id JOIN properties p ON p.id=t.property_id WHERE k.id=? AND p.manager_id=?').get(id,u.id))return json(res,404,{error:'Talep bulunamadı.'});db.prepare('UPDATE tickets SET status=?,reply=COALESCE(NULLIF(?,\'\'),reply),updated_at=? WHERE id=?').run(status,clean(b.reply).slice(0,500),now(),id);audit(u,`Destek talebi ${status.toLocaleLowerCase('tr-TR')} oldu`,'ticket',id);json(res,200,{ok:true}); }
async function bankApi(req,res) { const u=guard(req,res,'agent');if(!u)return;if(req.method==='GET')return json(res,200,{items:db.prepare('SELECT * FROM bank_matches WHERE manager_id=? ORDER BY id DESC LIMIT 50').all(u.id)});const b=await parse(req),reference=clean(b.reference).slice(0,160),amount=Number(b.amount);if(!reference||!Number.isFinite(amount)||amount<=0)return json(res,400,{error:'Havale açıklaması ve geçerli tutar girin.'});const r=db.prepare('INSERT INTO bank_matches(reference,amount,created_at,manager_id) VALUES(?,?,?,?)').run(reference,amount,now(),u.id);audit(u,'Havale hareketi eşleştirildi','bank_match',Number(r.lastInsertRowid),reference);json(res,201,{ok:true}); }
async function receipt(req,res) { const u=guard(req,res,'tenant');if(!u)return;const b=await parse(req),raw=String(b.data||'').split(',').pop()||'',bytes=Buffer.from(raw,'base64');if(!clean(b.fileName)||!bytes.length||bytes.length>10*1024*1024)return json(res,400,{error:'PDF, JPG veya PNG biçiminde en fazla 10 MB dosya yükleyin.'});const safe=path.basename(b.fileName).replace(/[^a-zA-Z0-9._-]/g,'_'),stored=`${Date.now()}_${safe}`;fs.writeFileSync(path.join(uploads,stored),bytes);db.prepare("UPDATE payments SET receipt_name=?,status='Dekont yüklendi' WHERE tenant_id=? AND period=?").run(stored,u.tenant_id,period());audit(u,'Dekont yüklendi','payment',u.tenant_id,safe);json(res,200,{ok:true,fileName:safe}); }
function receiptFile(req,res,fileName){const u=guard(req,res,'agent');if(!u)return;const safe=path.basename(fileName);if(safe!==fileName)return json(res,400,{error:'Geçersiz dosya adı.'});if(!db.prepare('SELECT 1 FROM payments pay JOIN tenants t ON t.id=pay.tenant_id JOIN properties p ON p.id=t.property_id WHERE pay.receipt_name=? AND p.manager_id=?').get(safe,u.id))return json(res,404,{error:'Dekont bulunamadı.'});const file=path.join(uploads,safe);if(!fs.existsSync(file))return json(res,404,{error:'Dekont dosyası bulunamadı.'});const types={'.pdf':'application/pdf','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg'};res.writeHead(200,{'Content-Type':types[path.extname(safe).toLowerCase()]||'application/octet-stream','Content-Disposition':`inline; filename="${safe}"`,'X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res);audit(u,'Dekont görüntülendi','payment',null,safe);}
async function advanceApi(req,res) { const u=guard(req,res);if(!u)return;if(req.method==='GET'){const sql=u.role==='tenant'?'SELECT a.*,t.name tenant FROM advance_requests a JOIN tenants t ON t.id=a.tenant_id WHERE a.tenant_id=? ORDER BY a.id DESC':'SELECT a.*,t.name tenant FROM advance_requests a JOIN tenants t ON t.id=a.tenant_id JOIN properties p ON p.id=t.property_id WHERE p.manager_id=? ORDER BY a.id DESC';return json(res,200,{requests:u.role==='tenant'?db.prepare(sql).all(u.tenant_id):db.prepare(sql).all(u.id)})}const b=await parse(req);if(u.role==='tenant'){const months=Number(b.months);if(![3,6,12].includes(months))return json(res,400,{error:'3, 6 veya 12 ay seçin.'});const tenant=db.prepare('SELECT rent FROM tenants WHERE id=?').get(u.tenant_id),r=db.prepare('INSERT INTO advance_requests(tenant_id,months,amount,note,created_at) VALUES(?,?,?,?,?)').run(u.tenant_id,months,tenant.rent*months,clean(b.note).slice(0,240),now());audit(u,'Peşin ödeme talebi oluşturuldu','advance_request',Number(r.lastInsertRowid));return json(res,201,{ok:true})}const id=Number(b.id),result=b.result==='Onaylandı'?'Onaylandı':'Reddedildi';if(!id||!db.prepare('SELECT 1 FROM advance_requests a JOIN tenants t ON t.id=a.tenant_id JOIN properties p ON p.id=t.property_id WHERE a.id=? AND p.manager_id=?').get(id,u.id))return json(res,404,{error:'Talep bulunamadı.'});db.prepare('UPDATE advance_requests SET status=?,review_note=?,reviewed_at=? WHERE id=?').run(result,clean(b.note).slice(0,240),now(),id);audit(u,`Peşin ödeme talebi ${result.toLocaleLowerCase('tr-TR')} oldu`,'advance_request',id);json(res,200,{ok:true}); }
async function structureApi(req,res) { const u=guard(req,res,'agent');if(!u)return;if(req.method==='GET')return json(res,200,{sites:db.prepare('SELECT * FROM sites WHERE manager_id=? ORDER BY id DESC').all(u.id),blocks:db.prepare('SELECT b.* FROM blocks b JOIN sites s ON s.id=b.site_id WHERE s.manager_id=? ORDER BY b.id DESC').all(u.id),units:db.prepare('SELECT un.* FROM units un JOIN blocks b ON b.id=un.block_id JOIN sites s ON s.id=b.site_id WHERE s.manager_id=? ORDER BY un.id DESC').all(u.id)});const b=await parse(req),kind=b.kind;if(kind==='site'){const name=clean(b.name).slice(0,120);if(!name)return json(res,400,{error:'Site/bina adı zorunludur.'});const r=db.prepare('INSERT INTO sites(name,address,block_count,created_at,manager_id) VALUES(?,?,?,?,?)').run(name,clean(b.address).slice(0,240),0,now(),u.id);audit(u,'Site/bina eklendi','site',Number(r.lastInsertRowid),name);return json(res,201,{ok:true})}if(kind==='block'){const siteId=Number(b.siteId),name=clean(b.name).slice(0,60);if(!siteId||!name||!db.prepare('SELECT 1 FROM sites WHERE id=? AND manager_id=?').get(siteId,u.id))return json(res,400,{error:'Geçerli site ve blok adı girin.'});const r=db.prepare('INSERT INTO blocks(site_id,name) VALUES(?,?)').run(siteId,name);db.prepare('UPDATE sites SET block_count=(SELECT COUNT(*) FROM blocks WHERE site_id=?) WHERE id=?').run(siteId,siteId);audit(u,'Blok eklendi','block',Number(r.lastInsertRowid),name);return json(res,201,{ok:true})}if(kind==='unit'){const blockId=Number(b.blockId),unitNo=clean(b.unitNo).slice(0,30);if(!blockId||!unitNo||!db.prepare('SELECT 1 FROM blocks bl JOIN sites s ON s.id=bl.site_id WHERE bl.id=? AND s.manager_id=?').get(blockId,u.id))return json(res,400,{error:'Geçerli blok ve daire numarası girin.'});const r=db.prepare('INSERT INTO units(block_id,unit_no,occupancy) VALUES(?,?,?)').run(blockId,unitNo,clean(b.occupancy)==='Dolu'?'Dolu':'Boş');audit(u,'Daire eklendi','unit',Number(r.lastInsertRowid),unitNo);return json(res,201,{ok:true})}json(res,400,{error:'Geçersiz yapı işlemi.'}); }
function logs(req,res) { const u=guard(req,res,'agent');if(!u)return;json(res,200,{items:db.prepare("SELECT l.*,COALESCE(us.full_name,'Sistem') actor FROM activity_logs l LEFT JOIN users us ON us.id=l.user_id WHERE l.user_id=? OR l.user_id IN (SELECT us2.id FROM users us2 JOIN tenants t ON t.id=us2.tenant_id JOIN properties p ON p.id=t.property_id WHERE p.manager_id=?) ORDER BY l.id DESC LIMIT 100").all(u.id,u.id)}); }
function staticFile(req,res) { let url=decodeURIComponent(req.url.split('?')[0]);if(url==='/')url='/index.html';if(url.startsWith('/uploads/')||url.split('/').some(seg=>seg.startsWith('.')&&seg!=='')){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Bulunamadı')}const file=path.resolve(root,`.${url}`);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Bulunamadı')}if(url==='/index.html'){const html=fs.readFileSync(file,'utf8').replace('href="styles.css"',`href="styles.css?v=${ASSET_VERSIONS['styles.css']}"`).replace('src="app.js"',`src="app.js?v=${ASSET_VERSIONS['app.js']}"`);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});return res.end(html)}const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.pdf':'application/pdf'};res.writeHead(200,{'Content-Type':types[path.extname(file).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res); }
http.createServer(async(req,res)=>{try{const pathname=req.url.split('?')[0];if(req.method==='GET'&&pathname.startsWith('/api/receipts/'))return receiptFile(req,res,decodeURIComponent(pathname.slice('/api/receipts/'.length)));const routes={'GET /api/health':(_req,response)=>json(response,200,{ok:true,service:'PusulaKira',time:now()}),'POST /api/auth/register-manager':registerManager,'POST /api/auth/login':login,'POST /api/auth/logout':logout,'GET /api/portal':portal,'PUT /api/profile':updateProfile,'PUT /api/profile/password':updatePassword,'POST /api/tenants':createTenant,'GET /api/tenants':tenantList,'POST /api/manager-actions':managerAction,'GET /api/announcements':announcementApi,'POST /api/announcements':announcementApi,'GET /api/tickets':ticketApi,'POST /api/tickets':ticketApi,'GET /api/bank-matches':bankApi,'POST /api/bank-matches':bankApi,'POST /api/payments/current/receipt':receipt,'GET /api/advance-requests':advanceApi,'POST /api/advance-requests':advanceApi,'GET /api/site-structure':structureApi,'POST /api/site-structure':structureApi,'GET /api/activity-logs':logs};const handler=routes[`${req.method} ${pathname}`];if(handler)return await handler(req,res);staticFile(req,res)}catch(error){const clientError=error.message==='İstek çok büyük.'||error.message==='Geçersiz JSON.';if(!clientError)console.error(error);if(!res.headersSent)json(res,clientError?400:500,{error:clientError?error.message:'Sunucu hatası.'})}}).listen(port,()=>console.log(`PusulaKira: http://localhost:${port}`));
